<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FaqsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">Is</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">More Expensive Than Cleaning On Your Own Wash Pad?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">No,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">is&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">less expensive</span> than cleaning on your own wash pad.</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Read more &rarr;</a></h2>',
            'locale' => 'en',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">Is</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">是否比自己的洗垫清洁更贵？</span></h2>',
            'embed' => '<h2><span style="color: #000000;">不,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">比您自己的洗垫清洁&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">便宜</span> than cleaning on your own wash pad.</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">阅读更多 &rarr;</a></h2>',
            'locale' => 'cn',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">Is</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">duurder dan schoonmaken met uw eigen waskussen?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Nee,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">is&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">minder duur</span> dan reinigen op uw eigen waskussen..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Lees meer &rarr;</a></h2>',
            'locale' => 'de',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">Is</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">duurder dan schoonmaken met uw eigen waskussen?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Nee,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">is&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">minder duur</span> dan reinigen op uw eigen waskussen..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Lees meer &rarr;</a></h2>',
            'locale' => 'es-us',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">Is</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">duurder dan schoonmaken met uw eigen waskussen?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Nee,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">is&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">minder duur</span> dan reinigen op uw eigen waskussen..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Lees meer &rarr;</a></h2>',
            'locale' => 'es',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">duurder dan schoonmaken met uw eigen waskussen?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Non,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">est&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">moins cher</span> que le nettoyage sur votre propre tampon de lavage.</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Lees meer &rarr;</a></h2>',
            'locale' => 'fr',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">आपके अपने वॉश पैड पर सफाई से अधिक महंगा है?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">नहीं,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">अपने स्वयं के वॉश पैड पर सफाई करने से&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">कम खर्चीला</span> que le nettoyage sur votre propre tampon de lavage.</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Lees meer &rarr;</a></h2>',
            'locale' => 'hi-in',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">は自分のウォッシュパッドで掃除するよりも高価ですか？</span></h2>',
            'embed' => '<h2><span style="color: #000000;">いいえ,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">は自分のウォッシュパッドで掃除するよりも &nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">安価</span> です。</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">続きを読む &rarr;</a></h2>',
            'locale' => 'jp',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2>Adakah <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">Lebih Mahal Daripada Pembersihan di Pad Basuh Sendiri?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">いいえ,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">は自分のウォッシュパッドで掃除するよりも &nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">安価</span> です。</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">続きを読む &rarr;</a></h2>',
            'locale' => 'ml',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">Is</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">duurder dan schoonmaken met uw eigen waskussen?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Nee,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">is&nbsp;<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">minder duur</span> dan reinigen op uw eigen waskussen..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Lees meer &rarr;</a></h2>',
            'locale' => 'mx',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="color: #000000;">ਕੀ</span>&nbsp;<span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">ਤੁਹਾਡੇ ਆਪਣੇ ਵਾੱਸ਼ ਪੈਡ ਦੀ ਸਫਾਈ ਨਾਲੋਂ ਵਧੇਰੇ ਮਹਿੰਗਾ ਹੈ?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">ਨਹੀਂ,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">is&nbsp;ਹਾਡੇ ਆਪਣੇ ਵਾੱਸ਼ ਪੈਡ \'ਤੇ ਸਾਫ ਕਰਨ ਨਾਲੋਂ<span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">ਘੱਟ ਮਹਿੰਗਾ</span> dan reinigen op uw eigen waskussen..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">ਹੋਰ ਪੜ੍ਹੋ &rarr;</a></h2>',
            'locale' => 'pa-pk',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">é mais caro do que limpar na sua própria almofada de lavagem?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Não,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">é <span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">mais barato</span> dan reinigen op uw eigen waskussen..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Leia mais &rarr;</a></h2>',
            'locale' => 'pt-br',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2>Является ли <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">более дорогим, чем мытье собственной подушечки для мытья посуды?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">Нет,</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;"><span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">дешевле</span> чем чистка собственной губкой..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">Читать дальше &rarr;</a></h2>',
            'locale' => 'ru',
        ]);

        DB::table('faqs')->insert([
            'faqid' => '11111111',
            'title' => '<h2><span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;">แพงกว่าการทำความสะอาดด้วยแผ่นซักของคุณเองหรือไม่?</span></h2>',
            'embed' => '<h2><span style="color: #000000;">ไม่</span> <span style="font-size: 1.15em; color: #227cbe;">C</span><span style="font-size: 0.9em; color: #227cbe; ">LEAN</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">A</span><span style =" font-size: 0.9em; color: #227cbe; ">S</span>&nbsp;<span style =" font-size: 1.15em; color: #227cbe; ">N</span><span style =" font-size: 0.9em; color: #227cbe; ">EW</span><sub style =" font-size: 1.1em; color: #227cbe; ">&reg;</sub>&nbsp;<span style="color: #000000;"><span style="box-sizing: border-box; font-family: Oswald, sans-serif; font-size: 20px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #f8f9fa; text-decoration: underline;">ถูกกว่า</span> กว่าการทำความสะอาดด้วยแผ่นซักของคุณเอง..</span><br /><a href="http://localhost:3000/posts/washpad-hydroblasting-vs-cleanasnew" aria-invalid="true">อ่านเพิ่มเติม &rarr;</a></h2>',
            'locale' => 'th',
        ]);
    }
}
