-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'es-us', title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'mx'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'es'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'fr'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'pt-br', title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'de'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'ru'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'hi-in', title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'pa-pk', title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'cn'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'jp'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'th'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';
-- insert into posts (locale, title, image_landing, embed, created_at, updated_at) select 'ml'   , title, image_landing, embed, created_at, updated_at from posts_copy1 where locale='en';


-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'es-us'	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'mx'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'es'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'fr'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'pt-br'	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'de'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'ru'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'hi-in'	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'pa-pk'	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'cn'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'jp'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'th'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
-- insert into what_we_cleans (locale, cleanid, title, image, embed, type, created_at, updated_at) select 'ml'   	, cleanid, title, image, embed, type, created_at, updated_at from what_we_cleans_copy1 where locale='en';
